spring:
  servlet:
    multipart:
      enabled: true # Enable multipart uploads
      file-size-threshold: 2KB # Threshold after which files are written to disk
      max-file-size: 200MB # Max file size
      max-request-size: 215MB # Max Request Size

file-storage-service:
  upload-directory: ${FILE_DIRECTORY:/} # All files uploaded through the REST API will be stored in this directory
  access-key: ${ACCESS_KEY:}